steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: [
        'build',
        '--builder=gcr.io/buildpacks/builder',
        '--env', 'GOOGLE_BUILDABLE=./services/world/cmd/world',
        '--publish',
        'europe-west3-docker.pkg.dev/petermalina/mongers/world-${BRANCH_NAME}'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'beta', 'run',
        'deploy', 'user',
        '--image', 'europe-west3-docker.pkg.dev/petermalina/mongers/world-${BRANCH_NAME}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--region', 'europe-west3',
#        '--service-account', 'application@petermalina.iam.gserviceaccount.com',
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'run',
        'services','update-traffic',
        '--platform', 'managed',
        '--region', 'europe-west3',
        'mongers-world', '--to-latest'
    ]